import { raw } from "@elurjs/kit/content";
import type { ElurTemplate } from "@elurjs/core";

export function ElurIonic(): ElurTemplate {
  return raw(`
<section class="home-section home-elur-ionic-section" id="elur-ionic">
    <div class="home-container">
      <div class="home-section-header animate-on-scroll">
        <div class="home-section-label" style="color:#fb923c">📱 Mobile Apps</div>
        <h2 class="home-section-title">Elur goes&nbsp;<span
            style="background:linear-gradient(135deg,#fb923c,var(--c-accent-3));-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent">mobile.</span>
        </h2>
        <p class="home-section-desc">
          <strong>Elur-Ionic</strong> bridges Elur reactivity with the full Ionic component library.
          Build native-quality mobile apps with signals, client-side routing, and&nbsp;<em>modular loading</em>.
          Since <strong>v2.0</strong>, the router uses the core Elur router (no <code>ion-router</code>), with <code>IonRouterOutlet</code>, <code>createTabsLayout</code>, and <code>createBottomTabBar</code> for tab navigation.
        </p>
      </div>

      <!-- Hero layout: text + code -->
      <div class="home-ionic-hero-layout animate-on-scroll">
        <div class="home-ionic-hero-text">
          <h3>Ionic Web Components.<br>Elur Reactivity.</h3>
          <p>
            Install <code
              style="font-family:var(--font-mono);font-size:0.85em;color:#fb923c;background:rgba(251,146,60,0.1);padding:2px 6px;border-radius:4px">@elurjs/ionic</code>
            and let the Vite plugin auto-register only the <code>&lt;ion-*&gt;</code> tags you use — or import bundles manually for full control.
          </p>
          <ul class="home-ionic-features-list">
            <li><span class="home-ionic-check">✓</span> Auto-registration via Vite plugin — zero manual setup</li>
            <li><span class="home-ionic-check">✓</span> Or import bundles manually: layout, forms, overlays, navigation…</li>
            <li><span class="home-ionic-check">✓</span> Core bootstrap registers only essential Ionic elements</li>
            <li><span class="home-ionic-check">✓</span> Routing via core Elur router + <code>IonRouterOutlet</code></li>
            <li><span class="home-ionic-check">✓</span> <code>createTabsLayout</code> &amp; <code>createBottomTabBar</code> for tab apps</li>
            <li><span class="home-ionic-check">✓</span> Compatible with Capacitor for true native deployment</li>
            <li><span class="home-ionic-check">✓</span> Signals-first — all state is reactive by default</li>
          </ul>
          <div class="home-ionic-install-box">
            <span><span class="dollar">$</span> npm install <span class="pkg">@elurjs/ionic</span></span>
          </div>
          <div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap;font-size:0.78rem;color:var(--c-text-3)">
            <span
              style="padding:6px 10px;border:1px solid var(--c-border);border-radius:999px;background:rgba(251,146,60,0.08)">Elur-Ionic
              2.1.0</span>
            <span
              style="padding:6px 10px;border:1px solid var(--c-border);border-radius:999px;background:rgba(96,165,250,0.08)">Elur
              3.6.2 compatible</span>
            <span
              style="padding:6px 10px;border:1px solid var(--c-border);border-radius:999px;background:rgba(52,211,153,0.08)">Ionic
              Core 8.x</span>
          </div>
        </div>

        <div class="home-ionic-code-panel">
          <div class="home-code-header">
            <div class="home-code-dots"><span></span><span></span><span></span></div>
            <span class="home-code-filename">main.ts</span>
          </div>
          <div class="home-code-body" tabindex="0" role="region" aria-label="Code example">
            <pre><span class="kw">import</span> { ElurComponent, html, mount, elurRouter } <span class="kw">from</span> <span class="str">"@elurjs/core"</span>;
<span class="kw">import</span> { IonRouterOutlet } <span class="kw">from</span> <span class="str">"@elurjs/ionic"</span>;

<span class="cmt">// Auto-generated by the Vite plugin — scans html\`\` templates</span>
<span class="cmt">// for &lt;ion-*&gt; tags and registers only what you use.</span>
<span class="kw">import</span> <span class="str">"virtual:elur-ionic/registration"</span>;

<span class="kw">import</span> { HomePage } <span class="kw">from</span> <span class="str">"./pages/HomePage"</span>;
<span class="kw">import</span> { TaskDetailPage } <span class="kw">from</span> <span class="str">"./pages/TaskDetailPage"</span>;

<span class="kw">const</span> router = <span class="fn">elurRouter</span>();

<span class="cmt">// Elur router + IonRouterOutlet (no ion-router needed)</span>
<span class="kw">const</span> outlet = <span class="kw">new</span> <span class="fn">IonRouterOutlet</span>([
  { path: <span class="str">"/"</span>,         component: (ctx) => <span class="kw">new</span> <span class="fn">HomePage</span>(ctx) },
  { path: <span class="str">"/task/:id"</span>, component: (ctx) => <span class="kw">new</span> <span class="fn">TaskDetailPage</span>(ctx) },
]);

<span class="kw">class</span> <span class="fn">App</span> <span class="kw">extends</span> <span class="type">ElurComponent</span> {
  <span class="fn">render</span>() {
    <span class="kw">return</span> <span class="fn">html</span><span class="str">\`&lt;ion-app&gt;\${outlet}&lt;/ion-app&gt;\`</span>;
  }
}

<span class="fn">mount</span>(<span class="kw">new</span> <span class="fn">App</span>(), <span class="str">"#app"</span>);</pre>
          </div>
        </div>
      </div>

      <!-- Feature cards -->
      <div class="home-ionic-features-grid">
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">⚡</span>
          <h4>Auto-Registration</h4>
          <p>The Vite plugin scans <code>html\`\`</code> templates for <code>&lt;ion-*&gt;</code> tags and generates
            registration imports automatically. Zero manual setup — or import bundles manually for full control.</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">📦</span>
          <h4>Tree-Shakeable Bundles</h4>
          <p>8 category bundles (layout, navigation, forms, lists, feedback, buttons, overlays, all) + per-component
            subpath imports. Minimal fixture = 11.3% of full bundle (gzip).</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">🎨</span>
          <h4>Reactive Overlays</h4>
          <p>Signal-based <code>createToast()</code>, <code>createAlert()</code>, <code>createLoading()</code>,
            <code>createActionSheet()</code>, <code>createPopover()</code>, <code>createModal()</code>,
            <code>createPicker()</code> — with <code>presented</code> and <code>result</code> signals, latest-wins
            semantics, and stale-result protection.</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">🗄️</span>
          <h4>Cache Policies</h4>
          <p>LRU/FIFO max eviction, TTL expiry, per-route overrides, and per-tab cache isolation. Keep pages alive
            across navigation or expire them automatically.</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">🧭</span>
          <h4>Core Router Integration</h4>
          <p>Single router authority — no competing Ionic/Elur routers. <code>IonRouterOutlet</code> +
            <code>IonBackButton</code> + reactive <code>canGoBack</code>. Deep linking, tab stacks, and history-api
            navigation work out of the box.</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">📱</span>
          <h4>Tab System</h4>
          <p><code>createTabsLayout()</code> wraps outlet + tab bar in <code>&lt;ion-tabs&gt;</code> with correct CSS
            layout. <code>createBottomTabBar()</code> with badges, CSS vars, layout options, and Stencil
            <code>selected</code> sync via <code>ref</code> + <code>effect</code>.</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">💾</span>
          <h4>Page-State Persistence</h4>
          <p>Opt-in serializable state across navigation. Preserve form inputs, scroll position, and component state
            when users navigate back and forth.</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">📲</span>
          <h4>Optional Capacitor</h4>
          <p><code>@elurjs/ionic/capacitor</code> subpath with zero web bundle cost (604 bytes). StatusBar,
            SplashScreen, Keyboard, Haptics, and App plugin wrappers with graceful web degradation (no-op on web).</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">🎭</span>
          <h4>Framework Delegate</h4>
          <p>Mount Elur templates and components inside Ionic overlays (modal, popover) via a Elur
            <code>FrameworkDelegate</code> — uses <code>mount()</code> to render and <code>unmount()</code> on
            dismiss.</p>
        </div>
        <div class="home-ionic-feature-card animate-on-scroll">
          <span class="home-ionic-feature-icon">🧪</span>
          <h4>Tested &amp; Verified</h4>
          <p>236 unit tests + 56 E2E tests with real <code>@ionic/core</code> (no mocks): navigation, lifecycle,
            overlays, custom elements, accessibility, and leak detection.</p>
        </div>
      </div>

      <!-- Bundle showcase -->
      <div class="home-ionic-bundle-section animate-on-scroll">
        <div class="home-ionic-bundle-header">
          <h3>Available Bundles — v2.1.0</h3>
          <span class="home-ionic-bundle-badge">
            <span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:#fb923c"></span>
            Tree-shakeable
          </span>
        </div>
        <div class="home-ionic-bundles-grid">
          <div class="home-ionic-bundle-pill">
            <div class="home-ionic-bundle-pill-name">layout</div>
            <div class="home-ionic-bundle-pill-desc">header, toolbar, title, content, footer, buttons</div>
          </div>
          <div class="home-ionic-bundle-pill">
            <div class="home-ionic-bundle-pill-name">navigation</div>
            <div class="home-ionic-bundle-pill-desc">menu, menu-button, menu-toggle</div>
          </div>
          <div class="home-ionic-bundle-pill">
            <div class="home-ionic-bundle-pill-name">forms</div>
            <div class="home-ionic-bundle-pill-desc">input, textarea, checkbox, radio, select, toggle, searchbar</div>
          </div>
          <div class="home-ionic-bundle-pill">
            <div class="home-ionic-bundle-pill-name">lists</div>
            <div class="home-ionic-bundle-pill-desc">list, item, label, thumbnail, avatar, card</div>
          </div>
          <div class="home-ionic-bundle-pill">
            <div class="home-ionic-bundle-pill-name">feedback</div>
            <div class="home-ionic-bundle-pill-desc">spinner, progress-bar, skeleton-text, badge, chip, note</div>
          </div>
          <div class="home-ionic-bundle-pill">
            <div class="home-ionic-bundle-pill-name">buttons</div>
            <div class="home-ionic-bundle-pill-desc">button, fab, fab-button, fab-list, ripple-effect</div>
          </div>
          <div class="home-ionic-bundle-pill">
            <div class="home-ionic-bundle-pill-name">overlays</div>
            <div class="home-ionic-bundle-pill-desc">modal, popover, toast, alert, action-sheet, picker</div>
          </div>
          <div class="home-ionic-bundle-pill" style="border-color:rgba(251,146,60,0.3);background:rgba(251,146,60,0.04)">
            <div class="home-ionic-bundle-pill-name" style="color:var(--c-text-2)">all</div>
            <div class="home-ionic-bundle-pill-desc">Everything — backward-compatible, ~35 KB gz</div>
          </div>
        </div>

        <div
          style="margin-bottom:16px;font-size:0.82rem;font-weight:600;color:var(--c-text-3);text-transform:uppercase;letter-spacing:1.5px">
          Migration guide (v1.x -> v2.x — major changes)</div>
        <div class="home-ionic-migration-box">
          <span class="home-diff-cmt">// Router — no more ion-router, single authority</span><br>
          <span class="home-diff-del">- import { elurIonicRouter } from "@elurjs/ionic";</span><br>
          <span class="home-diff-del">- const r = elurIonicRouter();</span><br>
          <span class="home-diff-add">+ import { elurRouter } from "@elurjs/core";</span><br>
          <span class="home-diff-add">+ import { IonRouterOutlet, createTabsLayout } from "@elurjs/ionic";</span><br>
          <span class="home-diff-add">+ const r = elurRouter();</span><br>
          <span class="home-diff-add">+ const outlet = new IonRouterOutlet(routes, { tabs: ["/home", "/profile"] });</span><br><br>
          <span class="home-diff-cmt">// Overlays — use* renamed to create*</span><br>
          <span class="home-diff-del">- const toast = useToast();</span><br>
          <span class="home-diff-add">+ import { createToast } from "@elurjs/ionic";</span><br>
          <span class="home-diff-add">+ const toast = createToast();</span><br><br>
          <span class="home-diff-cmt">// Components — auto-registration via Vite plugin</span><br>
          <span class="home-diff-del">- setupElurIonic(); // registered everything</span><br>
          <span class="home-diff-add">+ import "virtual:elur-ionic/registration"; // auto from templates</span>
        </div>

        <div style="margin-top:24px;display:flex;align-items:center;gap:16px;flex-wrap:wrap">
          <a href="https://github.com/elurjs/create-elur-app/tree/main/template-elur-ionic" target="_blank"
            rel="noopener" class="home-btn-secondary" style="padding:10px 22px;font-size:0.88rem">
            Starter Template
          </a>
          <a href="https://www.npmjs.com/package/@elurjs/ionic" target="_blank" rel="noopener" class="home-btn-primary"
            style="padding:10px 22px;font-size:0.88rem">
            View on npm
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"
              stroke-linecap="round" stroke-linejoin="round">
              <line x1="5" y1="12" x2="19" y2="12" />
              <polyline points="12 5 19 12 12 19" />
            </svg>
          </a>
          <a href="https://github.com/elurjs/elur-ionic" target="_blank" rel="noopener" class="home-btn-secondary"
            style="padding:10px 22px;font-size:0.88rem">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <path
                d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
            </svg>
            GitHub
          </a>
        </div>
      </div>
    </div>
  </section>
  `);
}
