import { readFile } from "node:fs/promises";
import { resolve, join } from "node:path";

export interface CssResult {
  /** Critical CSS to inline in <style> — blocks render. */
  inline: string;
  /** Deferred CSS <link> tag to inject — non-blocking. */
  deferredLink: string;
}

export async function getInlineCss(): Promise<CssResult> {
  const root = resolve(process.cwd());
  const stylesDir = join(root, "src", "styles");

  // Critical CSS: tokens, base, layout, home-critical — needed for first paint
  // (nav, hero, stats, ecosystem bar, footer, reset, design tokens, font-face)
  const criticalFiles = ["tokens.css", "base.css", "layout.css", "home-critical.css"];
  const criticalParts: string[] = [];
  for (const file of criticalFiles) {
    try {
      const content = await readFile(join(stylesDir, file), "utf8");
      criticalParts.push(content);
    } catch {
      // Skip missing files
    }
  }
  const inline = minifyCss(criticalParts.join("\n\n"));

  // Read the deferred CSS manifest generated by scripts/gen-deferred-css.ts
  let deferredLink = "";
  try {
    const manifestPath = join(root, "public", "css", "deferred-css.json");
    const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
    const href = `/css/${manifest.fileName}`;
    deferredLink =
      `<link rel="preload" as="style" href="${href}" onload="this.onload=null;this.rel='stylesheet'">` +
      `<noscript><link rel="stylesheet" href="${href}"></noscript>`;
  } catch {
    // Manifest not found — fall back to no deferred CSS
  }

  return { inline, deferredLink };
}

function minifyCss(css: string): string {
  return css
    // Remove comments
    .replace(/\/\*[\s\S]*?\*\//g, "")
    // Collapse whitespace
    .replace(/\s+/g, " ")
    // Remove spaces around selectors and braces
    .replace(/\s*([{}:;,>~+])\s*/g, "$1")
    // Remove trailing semicolons before }
    .replace(/;}/g, "}")
    // Trim
    .trim();
}
